version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /mnt/d/AhmedMahmoud/vscode-work/TaskNouraScriptingassignment/prometheus.yml:/etc/prometheus/prometheus.yml.template
      - /etc/node_exporter/tls:/etc/prometheus/tls
    ports:
      - "9090:9090"
    networks:
      - monitoring
    env_file:
      - ./prometheus.env  # Load the environment file
    entrypoint:
      - /bin/sh
      - -c
      - |
        envsubst < /etc/prometheus/prometheus.yml.template > /etc/prometheus/prometheus.yml && \
        exec prometheus --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" 
    networks:
      - monitoring
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  monitoring:
    driver: bridge
