version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /mnt/d/AhmedMahmoud/vscode-work/TaskNouraScriptingassignment/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/node_exporter/tls:/etc/prometheus/tls            # Mount Node Exporter's TLS directory
    ports:
      - "9090:9090"
    networks:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" 
    networks:
      - monitoring
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  monitoring:
    driver: bridge
