global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter_tls'
    scheme: https
    static_configs:
      - targets: ['$NODE_EXPORTER_IP:9100']
    basic_auth:
      username: admin
      password: $password
    tls_config:
      ca_file: /etc/prometheus/tls/node_exporter.crt
      cert_file: /etc/prometheus/tls/node_exporter.crt
      key_file: /etc/prometheus/tls/node_exporter.key
